export const CHANGE_QUERY = 'CHANGE_QUERY';
export const CHANGE_SEARCH_BY = 'CHANGE_SEARCH_BY';
export const CHANGE_SORT_BY = 'CHANGE_SORT_BY';
export const SWITCH_DISPLAY_MODE = "SWITCH_DISPLAY_MODE";
export const SEARCH_MODE = "SEARCH_MODE";
export const FETCH_FILMS = "FETCH_FILMS";
export const FETCH_FILMS_BY_ID = "FETCH_FILMS_BY_ID";